[variables]
POSTGRES_PASSWORD = { type = "password", length = 16 }
IDP_PARTNER_ENCRYPTION_KEY = { type = "password", length = 32 }
WALLET_BINDING_PARTNER_API_KEY = { type = "password", length = 32 }
OIDC_P12_PASSWORD = { type = "password", length = 16 }
INJI_WEB_DOMAIN = "inji-web.example.com"
MIMOTO_DOMAIN = "mimoto.example.com"
CERTIFY_DOMAIN = "certify.example.com"

[[config.domains]]
name = "inji-web"
port = 3004
host = "${INJI_WEB_DOMAIN}"

[[config.domains]]
name = "mimoto"
port = 8099
host = "${MIMOTO_DOMAIN}"

[[config.domains]]
name = "certify-nginx"
port = 80
host = "${CERTIFY_DOMAIN}"
